### ISSUE TITLE
Page not displaying correctly

### ISSUE THREAD

**Issue by sidehackcreative** [Luftgekuhlt-com/luft#1]
Page is not respecting the image gallery,  images are multiplying, etc. 

Admin:
http://luft-staging.sidehackcreative.com:8080/admin/pages/5

Preview:
http://luft-staging.sidehackcreative.com:8080/porsche-934-weissach-s-turbo-chameleon

**Comment by cvollmer** [comment]
@sidehackcreative is this good now?
