### ISSUE TITLE
Page Padding / Top Nav

### ISSUE THREAD

**Issue by sidehackcreative** [Luftgekuhlt-com/luft#10]
![TopNav](https://user-images.githubusercontent.com/56834505/68046285-89052880-fca9-11e9-8603-fcc5676e2d6e.png)

Page width: 1175px; Except full width images/sliders
Live content margins left and right 40px;

**Comment by cvollmer** [comment]
@sidehackcreative - updated the container content width. i am using a class '.content-wrap' for this.
