### ISSUE TITLE
global bread crumb style

### ISSUE THREAD

**Issue by sidehackcreative** [Luftgekuhlt-com/luft#14]
![Breadcrumb](https://user-images.githubusercontent.com/56834505/68172485-5ecb9900-ff3d-11e9-852d-1cfdd2e7115f.png)

**Display bread crumb on all child pages:** 
Galleries / {gallery name}
Past Events / {event name} / {storyline title}
News / {news article}
Videos / {video title}
Builds / {build name}

**Parent Only:** 
40px margin top

**Comment by cvollmer** [comment]
@sidehackcreative  - i have the basics of this in place and styled. there are obviously places that are not done yet that will need it, but the existing places have it to review.
