### ISSUE TITLE
Galleries Thumbs not linking

### ISSUE THREAD

**Issue by sidehackcreative** [Luftgekuhlt-com/luft#19]
It's only happening to the galleries that are assigned to a Past Event:

http://luft-staging.sidehackcreative.com:8080/galleries

**Comment by cvollmer** [comment]
@sidehackcreative - i made this go to a direct detail view of the gallery. i will handle them as a child of past event cases when i do the same for storyline. but if you go to the gallery from the galleries page it will be treated as a child of that for now.
