### ISSUE TITLE
H1 styles

### ISSUE THREAD

**Issue by sidehackcreative** [Luftgekuhlt-com/luft#23]
H1
Archivo Black Reg 400 34px
Normal Case

H2
Archivo Black Reg 400 30px
Normal Case

H3
Archivo Black Reg 400 24px
Normal Case

H4
Archivo Black Reg 400 21px
Normal Case

![Style-V3](https://user-images.githubusercontent.com/56834505/68447066-3d201b00-01a4-11ea-927d-fdbc7718e8e7.png)

**Comment by cvollmer** [comment]
@sidehackcreative  - updated these as best I could. when we talk we should discuss section headers
