### ISSUE TITLE
Left/Right Pane not working

### ISSUE THREAD

**Issue by sidehackcreative** [Luftgekuhlt-com/luft#25]
![Screen Shot 2019-11-09 at 8 39 21 AM](https://user-images.githubusercontent.com/56834505/68530254-7c498b80-02cc-11ea-8099-dd1126e93c2e.png)

Admin links:
http://luft-staging.sidehackcreative.com:8080/admin/pages/34
http://luft-staging.sidehackcreative.com:8080/admin/pages/36

**Comment by cvollmer** [comment]
@sidehackcreative - it was getting thrown off by my style to have html content max out at 1175px; i took that out and these were full screen. for now i made left and right panes layouts max out at 1175px;
